//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_201700404.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        public int idPartida { get; set; }
        public int idjugador { get; set; }
        public string ganador { get; set; }
        public string perdedor { get; set; }
        public Nullable<int> mov_ganador { get; set; }
        public Nullable<int> mov_perdedor { get; set; }
        public Nullable<int> fichas_ganador { get; set; }
        public Nullable<int> fichas_perdedor { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
