//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_201700404.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimiento
    {
        public int idMovimiento { get; set; }
        public string color { get; set; }
        public int fila { get; set; }
        public int col { get; set; }
    }
}
